language: go

sudo: true
notifications:
  email: true

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master
jobs:
  include:
    - stage: linux
      go: 1.8.1
      env:
        - DEPTESTBYPASS501=1
      os: linux
      install:
       - go get -u github.com/golang/dep/cmd/dep
       - go get -u github.com/golang/go/src/cmd/gofmt
      script:
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && go vet .
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && go fmt .
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && gofmt -e -s -w .
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && dep ensure -update -v
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && travis_wait 20 go test -p 10 -timeout 20m -v -cover -covermode atomic ./test/...
       - cp -Rf ../aws-architect ../../.. && cd ../../../aws-architect && go build -buildmode exe -pkgdir ./vendor .
    - stage: windows
      go: 1.8.1
      env:
        - DEPTESTBYPASS501=1
      os: windows
      install:
       - go get -u github.com/golang/dep/cmd/dep
       - go get -u github.com/golang/go/src/cmd/gofmt
      script:
       - go vet .
       - go fmt .
       - gofmt -e -s -w .
       - dep ensure -update -v
       - travis_wait 20 go test -p 10 -timeout 20m -v -cover -covermode atomic ./test/...
       - go build -buildmode exe -pkgdir ./vendor .
