language: go

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

go:
 - 1.8.1
 - 1.8.3
 - 1.8.5

install:
 - go get -u github.com/golang/dep/cmd/dep

script:
 - dep ensure -update -v
 - travis_wait 20 go test -p 10 -timeout 20m -v ./test/...
 - go vet .
 - go build -buildmode exe -pkgdir ./vendor .
